In [1]:
from bezier_utils.basic import extract_bezier_curves
from bezier_utils.linearity import is_approximately_linear_by_curvature
from bezier_utils.square_approx import draw_quadrilateral_with_square, get_quadrilateral_and_square_vertices
import numpy as np
from scipy.spatial.distance import euclidean
import matplotlib.pyplot as plt
from geomutils.core import mediate_points, mediate_lines, create_polygon_lines, calculate_angle
from geomutils.display import plot_polygon, plot_arrows_between_points
from geomutils.polygons import order_points_clockwise, build_connection_map, get_all_points, remove_finder

In [2]:
c, q = extract_bezier_curves('data/problems/frag0.svg')
lines = []
for curve in c:
    if is_approximately_linear_by_curvature(curve, tolerance=0.01):
        lines.append(np.array([curve[0], curve[-1]]))
unmediated_points = []
for line in lines:
    unmediated_points.append(line[0])
    unmediated_points.append(line[1])
mediated_points = mediate_points(unmediated_points, 0.5)
mediated_lines = mediate_lines(lines, mediated_points)
connections = build_connection_map(mediated_lines)
points = get_all_points(mediated_lines)
ordered_points = order_points_clockwise(points, connections)
remove_vertices = remove_finder(ordered_points)

In [3]:
def remove_elements(list1, list2):
    set2 = set(list2)
    result = [item for item in list1 if item not in set2]
    return result

In [4]:
flattened_ordered_points = remove_elements(ordered_points, remove_vertices)
flattened_polygon = create_polygon_lines(flattened_ordered_points)

In [5]:
get_quadrilateral_and_square_vertices(flattened_polygon)

[array([5.6649124, 3.4222874]),
 array([222.4353376,   3.4222874]),
 array([222.4353376, 220.1927126]),
 array([  5.6649124, 220.1927126])]